### ISSUE TITLE
Saving pubspec runs `pub get` instead of `flutter packages get` when Flutter project is in a sub-folder

### ISSUE THREAD

**Issue by anantakrroy** [Dart-Code/Dart-Code#1320]
I am unable to use the custom fonts because my pubspec.yaml file wouldn't save without an error for some reason. The error is this -

> [widgets_fun]

 

> pub get Resolving dependencies... Because widgets_fun depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.

> Flutter users should run flutter packages get instead of pub get. exit code 69`
Running flutter doctor -v does not throw any issues.
![screen shot 2018-11-27 at 2 00 17 pm](https://user-images.githubusercontent.com/20229180/49133205-296a0480-f305-11e8-9b59-2ae15dca8430.png)

Have enabled extension logging and flutter SDK has been detected.
[extension.txt](https://github.com/Dart-Code/Dart-Code/files/2623164/extension.txt)

My pubspec.yaml file
![screen shot 2018-11-28 at 12 04 02 pm](https://user-images.githubusercontent.com/20229180/49133352-caf15600-f305-11e8-9dc5-60364f1d3bae.png)

Interestingly, I also use an image asset as mentioned in the pubspec.yaml file and the image appears correctly. The error is shown on saving the file though.

**Comment by DanTup** [comment]
In the posted error, it says `widgets_fun` (which I believe is a folder name) but in the log, the project folder is `category_app` and I don't see `widgets_fun` anywhere. Do you have multiple projects open? If you set your log file path in the global User Settings, each VS Code window will overwrite each others logs, so you'll need to either repro with only a single VS Code window open or set the log only in the Workspace Settings for the affecting project.

**Comment by anantakrroy** [comment]
I have a single folder with multiple applications inside it. Is that not the right way to develop? I have removed all of the projects from that folder except widgets_fun. Also attached the updated extension log.
[extension_current.txt](https://github.com/Dart-Code/Dart-Code/files/2624047/extension_current.txt)

**Comment by DanTup** [comment]
> I have a single folder with multiple applications inside it. Is that not the right way to develop?

The answer is a bit complicated. In order go get all functionality to work correctly when you have multiple projects you're better opening each as a "workspace folder" in VS Code. However, since that behaves badly with nested folders (see https://github.com/Microsoft/vscode/issues/45470) I'd like as much functionality as possible to work even if you don't do this (and saving a pubspec certainly should work).

Can you confirm what your folder layout looks like, from the folder that you opened in VS Code, to where the pubspec you're modiying is. Is it in a sub-folder, for ex you have `/some/folder` opened in VS Code, and the pubspec is at `/some/folder/sub_project/pubspec.yaml`?

If you can repro this with a small sample you can share, that would help - though I'll try some things here to see if I can repro.

**Comment by anantakrroy** [comment]
The pubspec is not nested in any other folder. I am attaching the folder structure if that helps.
![screen shot 2018-11-28 at 5 01 12 pm](https://user-images.githubusercontent.com/20229180/49149158-5c28f280-f32f-11e8-802d-ac380abe3d9b.png)

**Comment by DanTup** [comment]
Thanks - this is what I suspected - the flutter project (`widgets_fun`) is in a sub-folder of the folder you opened (`flutterdev`). I think I understand that the issue is now, I'll see what I can do. Thanks!

**Comment by DanTup** [comment]
I've pushed a fix. If you'd like to test it out, you can grab the beta from here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.21.0-beta.2

Download the vsix file, run the `Extensions: Install from VSIX` command from the VS Code command palette and browse to the vsix file. Click `Reload` when prompted to activate the extension.

It should contain this fix as well as [the other changes going into the next release](https://dartcode.org/releases/v2-21/). You'll automatically be moved back to the stable releases on the next update.

Thanks for the help!

**Comment by anantakrroy** [comment]
I just checked the fix and the error "pub get Resolving dependencies... Because widgets_fun depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.
Flutter users should run flutter packages get instead of pub get. exit code 69`"  no longer appears . So we do have some progress here.The flutter packages get runs without errors with an exit code 0. However, the custom font is still not being loaded onto my UI button.

**Comment by anantakrroy** [comment]
Ok, I think there is no issue with the plugin. Because I ran `flutter run` from the terminal now, trying an `Raleway-ExtraBoldItalic` font but the font was not italicised. Any idea why there is an exclamation still present on this file name?
![screen shot 2018-11-28 at 7 13 07 pm](https://user-images.githubusercontent.com/20229180/49155789-d498af00-f341-11e8-8b9a-f6ce445bfc34.png)

**Comment by DanTup** [comment]
That's just the file icon for a YAML file! :-)

<img width="234" alt="screen shot 2018-11-28 at 1 52 02 pm" src="https://user-images.githubusercontent.com/1078012/49156262-d6984900-f314-11e8-8a65-003aab01518d.png">

It does look a bit misleading up there though!

If you think the font thing is a bug in Flutter (rather than an issue the font of something) add a comment to the original issue with details (including that the VS Code issue is solved and doesn't change anything) and we can re-open it.

**Comment by anantakrroy** [comment]
:) No wonder we learn something new everyday! I am a beginner and this exclamation does take me by surprise now :D ! I will try this on a new application and let me see if the font issue persists. Otherwise, I consider atleast the `flutter packages get` issue closed for now . Thanks a lot for sticking through!

**Comment by DanTup** [comment]
Cool, thanks for helping track it down. Do open issues if you hit any other problems :-)

**Comment by hemangjoshi37a** [comment]
Has anyone found any solution to this issue??

**Comment by DanTup** [comment]
@hemangjoshi37a this issue was closed as the problem above was fixed a long time ago. If you're having a problem that looks like this, please open a new issue with some specific details and [a log](https://dartcode.org/docs/logging/#capture-logs-command) and I can take a look.

**Comment by hemangjoshi37a** [comment]
ok sir. but can you just quote me the text in above messages that fixed the issue, please.

**Comment by DanTup** [comment]
@hemangjoshi37a the issue above was fixed by a code change in the extension. If you're on a recent version you already have it, so it's likely your issue has a different cause. Please open a new issue with a log and we can track down what's up.

**Comment by gussouzauni** [comment]
```Because flutter_sqlite depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version
  solving failed.

Flutter users should run `flutter pub get` instead of `pub get`.
```
How i can resolved it?

**Comment by DanTup** [comment]
@gussouzauni can you post a copy of your `pubspec.yaml` file?

**Comment by gussouzauni** [comment]
@DanTup

> name: flutter_sqlite
> description: A new Flutter project.
> 
> publish_to: "none"
> 
> version: 1.0.0+1
> 
> environment:
>   sdk: ">=2.7.0 <3.0.0"
> 
> dependencies:
>   flutter_svg:
>   dio: ^3.0.9
>   flutter_mobx: ^1.1.0+1
> 
>   mobx: ^1.2.1+1
>   flutter_modular: ^1.3.0
>   flutter:
>     sdk: flutter
> 
> dev_dependencies:
>   mockito: ^4.1.1
>   mobx_codegen: ^1.1.0+1
>   build_runner: ^1.10.0
>   flutter_test:
>     sdk: flutter
> 
> flutter:
>   uses-material-design: true
>   assets:
>     - assets/icons/icon_search.svg
>     - assets/icons/undraw1.svg
>     - assets/icons/undraw2.svg
> 
> vars:
>   clean: flutter clean
>   get: flutter pub get
>   runner: flutter pub run build_runner
> scripts:
>   mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
>   mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
>
