### ISSUE TITLE
Unable to run project after updating to flutter 1.20.0 

### ISSUE THREAD

**Issue by ahmadf20** [Dart-Code/Dart-Code#2702]
Hi, so I just updated my flutter SDK to the latest stable version of 1.20.0 after they announced the release not long ago. But, then I found out that now, I'm unable to run my existing project by hitting the F5 on vs code as I normally do. I don't know whats wrong, but it woks fine when I run "flutter run" on cmd.

It just shows as the image below without any further info

![image](https://user-images.githubusercontent.com/39834619/89440535-f3398500-d775-11ea-8907-8250430aabd6.png)

I also tried to create a new project but, the same thing happens.

Here's the dart code log:

<img width="721" alt="Screen Shot 2020-08-05 at 23 40 25" src="https://user-images.githubusercontent.com/39834619/89440627-17956180-d776-11ea-99d8-aa2513b88d59.png">

**Comment by blazeu** [comment]
I got 64 exit code too, I believe this is the error in the log that is relevant.

```
[12:02:57 AM] [FlutterRun] [Info] [Flutter] ..  in [MY_PROJECT_DIR]
[12:02:57 AM] [FlutterRun] [Info] [Flutter] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[12:02:57 AM] [FlutterRun] [Info] [Flutter]     PID: 1654
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [ +136 ms] executing: git -c log.showSignature=false log -n 1 --pretty=format:%H
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [  +41 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [        ] 0598acc722b752516b6a27b400e96cce8eb06f2b
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [        ] executing: git tag --contains HEAD
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [  +13 ms] Exit code 0 from: git tag --contains HEAD
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [   +1 ms] executing: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [  +11 ms] Exit code 128 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [        ] fatal: No names found, cannot describe anything.
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [   +2 ms] Could not interpret results of "git describe":
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [   +1 ms] executing: git rev-parse --abbrev-ref HEAD
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [        ] goshujin
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [   +3 ms] ensureAnalyticsSent: 1ms
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [   +5 ms] Running shutdown hooks
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [   +1 ms] Shutdown hooks complete
[12:02:58 AM] [FlutterRun] [Error] [Flutter] [   +4 ms] exiting with code 64
```

**Comment by DanTup** [comment]
There was an incorrect version number in Dart-Code's `FlutterCapabilities` that caused it to try and use a switch that isn't in todays stable release. I've fixed it and pushed an update (v3.13.2). You can get this by running the **Extensions: Check for Updates** command from the command palette and upgrade to v3.13.2 of both extensions. If the update doesn't show up (they can take a while), you can force it by:

- uninstall Flutter extension
- uninstall Dart extension
- restart VS Code
- install Dart extension (make sure to do this first)
- install Flutter extension

If you try to skip installing the Dart extension and just install Flutter, it may install an old version of the Dart extension (a VS Code marketplace caching bug). Once you're on v3.13.2 of both extensions, things should work again.

**Comment by VRspace4** [comment]
I didn't have to uninstall anything.

Restarting vscode worked for me after Flutter was updated.

**Comment by DanTup** [comment]
@VRspace4 yep, that's how it should be (though you probably could've also click the Reload button in the extensions list instead of a full restart). The uninstall/reinstall instructions were for those that couldn't see the update yet (as it sometimes can take 15min to propagate after release). Glad it's sorted!

**Comment by lbarqueira** [comment]
I restarted Vscode and it works.

**Comment by AbdoZDGaia** [comment]
![image](https://user-images.githubusercontent.com/57171672/89542930-99ca6800-d800-11ea-83f8-2ecd785b13fc.png)
![image](https://user-images.githubusercontent.com/57171672/89542977-a8188400-d800-11ea-870d-c24fb5650d0d.png)

I still get this error as of today after the update, btw i have uninstalled and re-installed dart then flutter.
whats the solution?

**Comment by DanTup** [comment]
@AbdoZDGaia try the things listed in https://github.com/Dart-Code/Dart-Code/issues/2706#issuecomment-669878016 - that seems to be a Flutter issue unrelated to this one.

**Comment by ubaidillahSriyudi** [comment]
@AbdoZDGaia i also got the same issue Execution failed for task ':app:compileFlutterBuildDebug'.

**Comment by Hamzakhan00** [comment]
(Android studio 4.0)
(Flutter SDK version 1.20.2 )
update flutter plugin 
clean the code 
then go to Pubspace.yaml
and click Pub upgrade
then Pub get

**Comment by sanjayrajsinh** [comment]
I use android studio and face same problem. after update flutter 1.20.0 project not able to run and dont give any error or log are blank

**Comment by DanTup** [comment]
If things aren't working in Android Studio, that's not the same issue as this (which was a bug in the VS Code extension). If things are failing in Android Studio without a clear message why, that should be raised at https://github.com/flutter/flutter-intellij/ (or if it can be reproduced from the command line, https://github.com/flutter/flutter/). Thanks!

**Comment by joharputr** [comment]
i solved with 
- delete packages.
- delete pubspec.lock
- flutter clean
- flutter pub get
