### ISSUE TITLE
lsp mode is very slow in big project

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3175]
**Describe the bug**
I have a workspace includes 4 flutter project. Every restart time it takes long time to show the type info, and when I hold `cmd` and click the Widget class, it takes long time to jump, even if not work. This is also happen in my colleague computer. It  works great in a small flutter project which includes few dart code.

**Versions (please complete the following information):**

 - VS Code version: 1.54.0-insider
 - Dart extension version: 3.20.1
 - Dart/Flutter SDK version: 1.22.4

One project  code line count:
![image](https://user-images.githubusercontent.com/41773861/109922925-140c8d80-7cf9-11eb-862b-e765fc82ad6d.png)

**Comment by tjx666** [comment]
It work fine if I disable lsp mode.

**Comment by DanTup** [comment]
> when I hold cmd and click the Widget class, it takes long time to jump

It sounds like the issue mentioned at https://github.com/Dart-Code/Dart-Code/issues/3102#issuecomment-773327117. This was a bug in the LSP server where opening a new file, or holding Ctrl and hovering over a symbol could trigger some expensive work in the server.

This has been fixed, although the fix did not make the Flutter 2.0 stable release. If you can easily test with the dev/master channel of Flutter temporarily, I'd be interested to know if you still see issues there.

Thanks!

**Comment by tjx666** [comment]
This issue still exits in flutter 2.0.1, after long time analyzing, the type info can show quickly when I hover cursor to class name, but cmd + click still take almost one minute to jump it's denifition.

**Comment by DanTup** [comment]
That sounds like the issue described above. The fix did not make Flutter 2.0 (or the minor release 2.0.1). It would likely only show up in the next (non-hotfix) stable release.

If you are able to easily test with dev/master channels, I'd be interested to know if the issue is still present there.

**Comment by rrousselGit** [comment]
:wave:

I'm on an up-to-date master channel and still have the issue

**Comment by DanTup** [comment]
@rrousselGit there was a recent change that re-introduced a very similar bug to the original one (https://github.com/dart-lang/sdk/issues/45633). My fix for that landed yesterday (https://github.com/dart-lang/sdk/commit/e8d53cff924214ea8dd20b36bb82f7d2dde7a131). That probably hasn't rolled into Flutter yet, but I'm interested to know if you still see issues once it has (and if so, I'd be interested in getting some logs - or if you can repro on something public, trying to reproduce it here).

**Comment by rrousselGit** [comment]
That issue is indeed very similar to what I've been facing for a couple of weeks, with the "problems" tab randomly refreshing for no apparent reason.  
For reference, this has been especially flagrant when interacting with the flutterfire repository.

I've also seen cases where saving a file "blocks": the white dot that means "unsaved changes" stays for a long time. And often, a snackbar appears with a message that says the formatting is taking too long.  
Usually using the "reload window" command fixes it, but after some time, the issue reappears.

**Comment by DanTup** [comment]
> I've also seen cases where saving a file "blocks": the white dot that means "unsaved changes" stays for a long time. And often, a snackbar appears with a message that says the formatting is taking too long.

I saw that once recently too, and was not able to reproduce it. It's possible it's related to this, although I would expect it to still finish fairly quickly. If you still see that after the above fix rolls in (and even better if you have logs enabled to capture it) I'd definitely like to know (I've seen some other reports of it, though all on stable where they could be seeing it from the original issue that was fixed after it branched).
