### ISSUE TITLE
CPU 100% and intellisense, format, fold code does not work

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3359]
In a multiple flutter project workspace, every time I open it,  dart cost 100% cpu, and the dart file has no intellisense, both format and code fold ability doesn't work. I have no idea how to deal with it.

It seems after very long time(about 30 minutes), It starts to work.

Version info:

```
VSCode: 1.57.0-insider (Universal)
OS: Darwin x64 20.4.0
Dart extension: v3.22.0
Flutter:  1.22.4
Dart SDK: 2.10.4
```

![image](https://user-images.githubusercontent.com/41773861/119459351-2cc49680-bd70-11eb-9f35-179c65d6c0f9.png)

![image](https://user-images.githubusercontent.com/41773861/119459609-6dbcab00-bd70-11eb-9c71-6ff45d7c50ea.png)

**Comment by tjx666** [comment]
I know I may not provide enough info to help fix it, please tell me what can I do for it.

**Comment by DanTup** [comment]
Can you run `code --status` while VS Code is in that state, and provide the output here? Thanks!

**Comment by tjx666** [comment]
@DanTup 

```
❯ code-insiders --status
Version:          Code - Insiders 1.57.0-insider (286b643ecd231f66f3f2e67e1456f3c601838b46, 2021-05-25T07:05:41.840Z)
OS Version:       Darwin x64 20.5.0
CPUs:             Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)
Memory (System):  16.00GB (0.52GB free)
Load (avg):       4, 4, 3
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id a38bd4e3-f812-45a8-b0aa-96f5de5940ff
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    3      131    3475  code-insiders main
    1       82    3478     gpu-process
    0       33    3480     utility
    0      147    3762     shared-process
    0       33    3763       ptyHost
    0        0    4517         /usr/local/bin/zsh
    0        0    4780           bash /usr/local/bin/code-insiders --status
    2       33    4790             electron_node cli.js 
    3      279    3897     window (background_panel.dart — GaodingCollage (Workspace))
    2      147    3898       extensionHost
    0       33    3914         electron_node server.js 
    0       82    3916         electron_node server.js 
   99      246    3923         /Users/yutengjing/apps/flutter/1.22.4/bin/cache/dart-sdk/bin/dart /Users/yutengjing/apps/flutter/1.22.4/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.22.0
    0        0    3924         bash /Users/yutengjing/apps/flutter/1.22.4/bin/flutter daemon
    0      147    3944           /Users/yutengjing/apps/flutter/1.22.4/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/yutengjing/apps/flutter/1.22.4/packages/flutter_tools/.packages /Users/yutengjing/apps/flutter/1.22.4/bin/cache/flutter_tools.snapshot daemon
    0        0    3987             /usr/bin/script -t 0 /dev/null xcrun xcdevice observe --both
    0       33    3988               /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
    0       33    3899       watcherService
    0       33    3901       searchService

Workspace Stats: 
|  Window (background_panel.dart — GaodingCollage (Workspace))
|    Folder (gd_asset): 391 files
|      File types: txt(20) png(18) mp4(18) xml(15) jar(12) properties(9)
|                  json(8) dart(6) lock(5) java(4)
|      Conf files:
|    Folder (xxx_yyy1): 381 files
|      File types: txt(20) png(18) xml(15) jar(12) dart(12) properties(9)
|                  json(8) lock(5) java(4) class(4)
|      Conf files:
|    Folder (xxx_yyy2): 616 files
|      File types: dart(102) png(36) txt(20) xml(19) properties(15) jar(12)
|                  json(11) lock(10) java(6) gitignore(5)
|      Conf files:
|    Folder (xxx_yyy3): 1528 files
|      File types: png(610) md5(84) sha1(84) xml(61) json(52) mp4(36) aar(22)
|                  pom(21) properties(17) h(17)
|      Conf files:
|    Folder (xxx_yyy4): 4086 files
|      File types: png(375) class(287) dex(198) json(172) xml(168) flat(125)
|                  h(94) txt(80) jar(78) java(38)
|      Conf files: launch.json(1)
|      Launch Configs: dart
|    Folder (xxx_yyy5): 5414 files
|      File types: so(468) json(406) hpp(377) xml(240) h(202) png(168)
|                  txt(148) fs(144) inl(134) flat(118)
|      Conf files: cmake(43) launch.json(1) settings.json(1) makefile(1)
|      Launch Configs: dart
```

**Comment by DanTup** [comment]
@tjx666 thanks! I missed that you're still on Flutter 1.22.4. That version is a little out of date now and there have been many fixes to the analysis server since. Could you try on the latest version of Flutter (2.2) and see if the issue persists?

Thanks!

**Comment by tjx666** [comment]
@DanTup 

I test with flutter 2.2, I takes only about 1 minutes to analyze. But this project is my company project, It may be upgrade to 2.2 recently several months. But Is there anythings I can do with it without upgrade flutter?

**Comment by DanTup** [comment]
I don't think so. It seems like you're probably hitting a bug in the analysis server that has been fixed, but the analysis server and the Dart SDK versions must be the same, and the Dart SDK and Flutter SDK versions must also be the same.

I think the best path forward would be to upgrade. Flutter 2 does include fixes to help migrate code (see https://flutter.dev/docs/development/tools/flutter-fix), although I appreciate it's probably still not a trivial task. Unfortunately I can't think of any other solutions in the meantime.

**Comment by tjx666** [comment]
In fact, the day before yesterday, this project didn't cost so long time to analyze in my own git branch. Yesterday, I toggle my  git branch to master, I start to occur this issue. And then I try to toggle back to my own branch, but this issue still exists.

**Comment by DanTup** [comment]
@tjx666 do you mean on Flutter 2.2? Or still on the older version? I'm not sure why it would be inconsistent, but it's only worth trying to debug if it's still occurring on Flutter 2.2 as there have been several performance improvements to the LSP server in Flutter 2.2.

**Comment by tjx666** [comment]
@DanTup  all on old version.
