### ISSUE TITLE
Isolates appear as "paused on entry" even if they're not paused

### ISSUE THREAD

**Issue by simolus3** [Dart-Code/Dart-Code#5397]
**Describe the bug**

When spawning new isolates at the start of an application, these isolates are mistakenly viewed as "paused on entry" in the call stack of the debugging view.

```dart
import 'dart:async';
import 'dart:isolate';

void main() async {
  final isolates = <Isolate>[];

  for (var i = 0; i < 10; i++) {
    isolates.add(await Isolate.spawn(
      (_) {
        print('isolate $i started');
        Timer.periodic(const Duration(minutes: 10), (_) {});
      },
      null,
    ));
  }

  await Future.delayed(Duration(seconds: 2));
  print('at resumed state');
  Timer.periodic(const Duration(minutes: 10), (_) {});
}
```

Setting a breakpoint on the `print` in line 18 and running this Dart program in VS Code will show most isolates as "paused on entry" (usually all of them, but not always. Maybe this is a race condition?).
Unfortunately, this is not just a cosmetic issue. It also affects the pause button in the button bar of the debugger, which will now interact with the new isolates instead of pausing / resuming the main isolate like it usually would.

**Expected behavior**
The isolates (except for `main` paused on a breakpoint) are all running and should be displayed as such.

I've attached a VM service to print the isolate's state shortly after hitting the breakpoint, the isolates are listed as running there. So I think this may be an issue in the extension (as opposed to something in the vm service).

**Screenshots**

Immediately after program start, all secondary isolates are shown as "Paused on entry". Then afterwards they're showing up as "".

![Image](https://github.com/user-attachments/assets/eca714d7-9ced-42ce-be17-799d5bf93b8c)

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.102.0
Flutter extension: 3.102.0 (not activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.96.3

Workspace type: Dart (LSP)
Workspace name: vscode_startup_issue

Dart (3.6.1): /opt/homebrew/Cellar/dart/3.6.1/libexec
Flutter (3.27.2): /Users/simon/fvm/versions/stable (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/opt/homebrew/Cellar/dart/3.6.1/libexec/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.6.1 (stable) (Tue Jan 7 09:50:00 2025 -0800) on "macos_arm64"
- on macos / Version 15.2 (Build 24C101)
- locale is de-DE

#### Project info

- sdk constraint: '^3.6.1'
- dependencies: sqlite_async, vm_service
- dev_dependencies: lints, test

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                     |
| -----: | ---: | -----------: | -------------------------------------------------------------------------------- |
| 116 MB | 0.0% |        22:01 | dart devtools                                                                    |
|  30 MB | 0.0% |        38:41 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/szh7dcqvfD8=       |
| 231 MB | 0.0% |        38:42 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.102.0 |
| 581 MB | 0.0% |        30:56 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.102.0 |
|  33 MB | 0.0% |        38:42 | dart tooling-daemon --machine                                                    |
|  64 MB | 0.0% |        30:56 | dart tooling-daemon --machine                                                    |
|  72 MB | 0.0% |        38:42 | flutter_tools.snapshot daemon                                                    |

</details>

**Comment by DanTup** [comment]
I don't seem to reproduce this, I see them all as paused on the breakpoint:

![Image](https://github.com/user-attachments/assets/f5867346-049c-459e-b4c4-24c75bc7ead3)

 Could you try capturing debugging logs while reproducing this?

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here, in a [gist](https://gist.github.com/), or email to me at logs@dartcode.org.

Thanks!

**Comment by DanTup** [comment]
Sorry, I had my breakpoint on the wrong print :) I can repro.. investigating!

**Comment by simolus3** [comment]
Thanks for the quick response 👍 I now see that my description was also ambigious..

**Comment by DanTup** [comment]
Hmmm, the DAP traffic looks good here:

[dap.txt](https://github.com/user-attachments/files/18524361/dap.txt)

If I filter to just the lines containing one of the threads, it looks like this:

```
[5:17:21 PM] [DAP] [Info] <== {"seq":21,"type":"event","body":{"reason":"started","threadId":3},"event":"thread"}
[5:17:21 PM] [DAP] [Info] <== {"seq":43,"type":"event","body":{"allThreadsStopped":false,"reason":"entry","threadId":3},"event":"stopped"}
[5:17:21 PM] [DAP] [Info] <== {"seq":78,"type":"event","body":{"allThreadsContinued":false,"threadId":3},"event":"continued"}
```

So while it did pause-on-entry, it continues immediately after. I'll try to reproduce with VS Code's MockDebug, this could be a VS Code bug.

**Comment by DanTup** [comment]
I can reproduce this in MockDebug. I've filed https://github.com/microsoft/vscode/issues/238591

**Comment by Albert221** [comment]
This is particularly annoying if you're using Drift in your application, which handles DB connection through an isolate. The debug bar in VS Code is almost always appearing to be in the paused state and I have to manually resume program that was never paused to begin with.

**Comment by DanTup** [comment]
@Albert221 unfortunately we can't fix it here, it's a VS Code issue - please add 👍 to https://github.com/microsoft/vscode/issues/238591

**Comment by Albert221** [comment]
BTW @DanTup I believe the above one is missing from [Upstream issues](https://dartcode.org/upstream-issues/)

**Comment by DanTup** [comment]
@Albert221 I've added it now, thanks!

**Comment by luishugoooo** [comment]
> This is particularly annoying if you're using Drift in your application, which handles DB connection through an isolate. The debug bar in VS Code is almost always appearing to be in the paused state and I have to manually resume program that was never paused to begin with.

Exactly the same issue, super annoying

**Comment by DanTup** [comment]
Unfortunately there's not much I can do about this until the VS Code issue is fixed. If you're affected by this, please add your 👍  to https://github.com/microsoft/vscode/issues/238591

**Comment by Mercutio1243** [comment]
I also face this issue, which I did not have last year. Is there a workaround such as downgrading VS Code to earlier versions to avoid this?

**Comment by DanTup** [comment]
> I also face this issue, which I did not have last year. Is there a workaround such as downgrading VS Code to earlier versions to avoid this?

Unfortunately I don't know of any workarounds or what versions of VS Code introduced it. There is a comment at https://github.com/microsoft/vscode/issues/238591#issuecomment-3138273861 that suggests it might have been a result of https://github.com/microsoft/vscode/pull/197397 which was added in Nov 2023, so it's possible a version from back then might work - however the current version of Dart-Code might not work with VS Code that far back.

**Comment by sprite2005** [comment]
I think I'm suffering from the same issue. I am using supabase_flutter and when I call an edge function with supabaseClient.functions.invoke it spawns a _compute isolate which starts paused and I have to resume it manually for the network request to go through.

**Comment by DanTup** [comment]
VS Code has made a fix for this and it's in the latest _Insiders_ build. Is anyone that could reproduce this able to confirm that it's fixed there? (You'll need to ensure you're on the latest insiders and restart after it installs the update).

The only repro I had was from MockDebug so it's not the best test that this is solved.

**Comment by simolus3** [comment]
I can't reproduce this issue with the latest insider build and the snippet I've posted in the original issue description. Since it still reproduces for me on VS Code stable, it looks like the fix is working 👍 

Should I close this issue or will that happen with the next release?

**Comment by DanTup** [comment]
Great, thanks for confirming! I'll close this now.

**Comment by easy-Coder** [comment]
@DanTup I still faced this issue by the way.

<img width="310" height="418" alt="Image" src="https://github.com/user-attachments/assets/5be5aa72-ca92-472a-a6a2-f573546bbd9e" />

I'm using the latest flutter version. also latest VS code and Dart Code extension version as i just updated it.

**Comment by DanTup** [comment]
@easy-Coder are you using VS Code stable or Insiders? Currently the fix is only in Insiders (see my comments a few above). Usually VS Code releases around 1 week into each month, so I would expect the fix to be in stable in around a fortnight.

**Comment by easy-Coder** [comment]
@DanTup I'm using the stable version. I will wait for the update. Thank you for your response

**Comment by NBA2K1** [comment]
I'm experiencing this bug right now.

VSCodium:
```
Version: 1.106.37943
Commit: 03d61e1799ba4597c64a6c0ae65316d95b2c2937
Date: 2025-11-27T00:03:42.214Z
Electron: 37.10.2
ElectronBuildId: undefined
Chromium: 138.0.7204.251
Node.js: 22.21.1
V8: 13.8.258.32-electron.0
OS: Linux x64 6.14.0-36-generic
```

&nbsp;

Dart Extension:
```
Name: Dart
Id: Dart-Code.dart-code
Description: Dart language support and debugger for Visual Studio Code.
Version: 3.122.0
Publisher: Dart-Code
VS Marketplace Link: https://open-vsx.org/vscode/item?itemName=Dart-Code.dart-code
```

```
$ dart --version
Dart SDK version: 3.10.1 (stable) (Tue Nov 18 11:02:31 2025 -0800) on "linux_x64"
```

**Comment by DanTup** [comment]
@NBA2K1 could you provide a code sample that reproduces this, along with a log file captured following the instructions in [this comment above](https://github.com/Dart-Code/Dart-Code/issues/5397#issuecomment-2610408352)? Thanks!

**Comment by NBA2K1** [comment]
> [@NBA2K1](https://github.com/NBA2K1) could you provide a code sample that reproduces this, along with a log file captured following the instructions in [this comment above](https://github.com/Dart-Code/Dart-Code/issues/5397#issuecomment-2610408352)? Thanks!

I can reproduce it with the same code sample as above.

<img width="1014" height="950" alt="Image" src="https://github.com/user-attachments/assets/9ae50a4a-c3d3-4ddf-a4a5-ce51b96221f2" />

&nbps;

Here's my log file:

[Dart-Code-Log-2025-11-04 02-44-55.txt](https://github.com/user-attachments/files/24091532/Dart-Code-Log-2025-11-04.02-44-55.txt)

**Comment by DanTup** [comment]
@NBA2K1 thanks! A similar issue also came up at https://github.com/Dart-Code/Dart-Code/issues/5829 and while debugging that I reproduced what I think is the issue you see here - it appears to be the same VS Code bug again.

I've opened https://github.com/microsoft/vscode/issues/280933 with a repro of that issue using their Mock Debug package - please add 👍 to that issue.

But it turns out there is also another issue (which is what https://github.com/Dart-Code/Dart-Code/issues/5829 really was about) where isolates can hang at startup. That issue is still being investigated.

Thanks!
