### ISSUE TITLE
The Dart Tooling Daemon connection has terminated.

### ISSUE THREAD

**Issue by SenexTech** [Dart-Code/Dart-Code#5794]
**Describe the bug**
When you build any app using Flutter, in my case I created a new app using the empty app template that comes with Flutter/VS Code.  So to clarify if you create a new app using VS Code (View/Command Pallete/Empty Application) then select Run the app will build successfully and run on my real Android phone. It could be a few minutes latter that the app exits and displays this error. This happens on two different Android phones and two different USB cables. I'm also getting the error 'Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: The pipe is being closed. , errno = 232)' which may be caused by the daemon exiting?

**To Reproduce**
1. create a new app using VS Code (View/Command Pallete/Empty Application)
2. Select Run the app (start debuging) and theapp will build successfully and run on my real Android phone.
3. Some time latter (could be a couple ofminutes)  I get a popup message saying "The Dart Tooling Daemon connection has terminated."
.

**Expected behavior**
The app should continue to run in debug mode without any errors and stay connected to device

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

```text
Dart Code extension: 3.122.0
Flutter extension: 3.122.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.105.1

Workspace type: Flutter (LSP)
Workspace name: flutter_application_1

Dart (3.9.2): C:\Users\pcira\dev\flutter\bin\cache\dart-sdk
Flutter (3.35.7): C:\Users\pcira\dev\flutter (Pixel 7 Pro (android-arm64/android))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\pcira\dev\flutter\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.9.2 (stable) (Wed Aug 27 03:49:40 2025 -0700) on "windows_x64"
- on windows / "Windows 11 Pro" 10.0 (Build 26200)
- locale is en-US

#### Project info

- sdk constraint: '^3.9.2'
- dependencies: flutter
- dev_dependencies: flutter_lints, flutter_test

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|  28 MB |  -- |              | dart.exe     |
| 111 MB |  -- |              | dart.exe     |
| 121 MB |  -- |              | dart.exe     |
|  95 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Users\pcira\dev\flutter\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.35.7, on Microsoft Windows [Version 10.0.26200.7171], locale en-US) [358ms]
    • Flutter version 3.35.7 on channel stable at C:\Users\pcira\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision adc9010625 (3 weeks ago), 2025-10-21 14:16:03 -0400
    • Engine revision 035316565a
    • Dart version 3.9.2
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-lldb-debugging

[√] Windows Version (11 Pro 64-bit, 25H2, 2009) [1,411ms]

[√] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [3.4s]
    • Android SDK at C:\Users\pcira\AppData\Local\Android\sdk
    • Emulator version 36.2.12.0 (build_id 14214601) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: C:\Program Files\java\jdk-17.0.12\bin\java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
    • All Android licenses accepted.

[√] Chrome - develop for the web [109ms]
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.14.20) [106ms]
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.14.36705.20
    • Windows 10 SDK version 10.0.26100.0

[√] Android Studio (version 2025.2.1) [9ms]
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.8+-14196175-b1038.72)

[√] VS Code (version 1.105.1) [6ms]
    • VS Code at C:\Users\pcira\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.122.0

[√] Connected device (4 available) [637ms]
    • Pixel 7 Pro (mobile) • 2B021FDH300DXJ • android-arm64  • Android 16 (API 36)
    • Windows (desktop)    • windows        • windows-x64    • Microsoft Windows [Version 10.0.26200.7171]
    • Chrome (web)         • chrome         • web-javascript • Google Chrome 142.0.7444.136
    • Edge (web)           • edge           • web-javascript • Microsoft Edge 142.0.3595.53

[√] Network resources [1,346ms]
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment]
@SenexTech when you get the message "The Dart Tooling Daemon connection has terminated" is there an "Open Log" button on the notification? If so, are you able to open it and see if there are any errors printed towards the end of the log?

(cc @bkonyi - from the description above it sounds like the app is also terminating - I don't know if DTD crashing is the cause of the app terminating, or if it might be the other way around?)

**Comment by bkonyi** [comment]
> (cc @bkonyi - from the description above it sounds like the app is also terminating - I don't know if DTD crashing is the cause of the app terminating, or if it might be the other way around?)

It's hard to say without more information. I'm not sure how DTD could crash as the result of a application crashing or vice versa.

**Comment by SenexTech** [comment]
Thanks for the quick response guys.  There is a log button. I have copied the lower third below.  I been through the whole log and see no errors.  Also, when when the daemon exits or when I get the OS Error: The pipe is being closed error the app on the phone keeps on running with no issues.  However, it loses connection to VS so I can't debug any more.


```
{"id":1,"jsonrpc":"2.0","result":null}
[3:22:01 PM] [Analyzer] [Info] <== Content-Length: 7026
Content-Type: application/vscode-jsonrpc; charset=utf-8
[3:22:01 PM] [Analyzer] [Info] <== {"id":2,"jsonrpc":"2.0","method":"client/registerCapability","params":{"registrations":[{"id":"0","method":"textDocument/prepareCallHierarchy","registerOptions":{"documentSelector":[{"language":"dart","scheme":"file"},{"language":"dart","scheme":"dart-macro+file"}]}},{"id":"1","method":"textDocument/codeAction","registerOptions":{"codeActionKinds":["source","source.organizeImports","source.fixAll","source.sortMembers","quickfix","refactor"],"documentSelector":[{"language":"dart","scheme":"file"},{"language":"dart","scheme":"dart-macro+file"}]}},{"id":"2","method":"textDocument/codeLens","registerOptions":{"documentSelector":[{"language":"dart","scheme":"file"},{"language":"dart","scheme":"dart-macro+file"}]}},{"id":"3","method":"textDocument/completion","registerOptions":{"completionIt…
[3:22:01 PM] [Analyzer] [Info] ==> Content-Length: 72
[3:22:01 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":2,"result":null,"clientRequestTime":1762978921885}
[3:22:02 PM] [DevTools] [Info] <== {"event":"server.started","method":"server.started","params":{"host":"127.0.0.1","port":9100,"pid":19392,"protocolVersion":"1.2.0"}}
[3:22:03 PM] [Analyzer] [Info] <== Content-Length: 601
Content-Type: application/vscode-jsonrpc; charset=utf-8
[3:22:03 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.connected","params":{"version":"0.6.1","pid":13428}}]
[3:22:03 PM] [FlutterDaemon] [Info] ==> [{"id":"1","method":"device.enable"}]
[3:22:03 PM] [FlutterDaemon] [Info] ==> [{"id":"2","method":"emulator.getEmulators"}]
[3:22:03 PM] [FlutterDaemon] [Info] ==> [{"id":"3","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"C:\\Users\\pcira\\Desktop\\flutter_application_1"}}]
[3:22:03 PM] [FlutterDaemon] [Info] ==> [{"id":"4","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"C:\\Users\\pcira\\Desktop\\flutter_application_1\\flutter_application_2"}}]
[3:22:03 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.logMessage","params":{"level":"status","message":"Device daemon started."}}]
[3:22:03 PM] [FlutterDaemon] [Info] <== [{"id":"1"}]
[3:22:03 PM] [FlutterDaemon] [Info] <== [{"id":"3","result":{"platforms":["web","android","ios","linux","macos","windows"],"platformTypes":{"web":{"isSupported":true},"android":{"isSupported":true},"ios":{"isSupported":true},"linux":{"isSupported":true},"macos":{"isSupported":true},"windows":{"isSupported":true},"fuchsia":{"isSupported":false,"reasons":[{"reasonText":"the Fuchsia feature is not enabled","fixText":"Run \"flutter config --enable-fuchsia\"","fixCode":"config"},{"reasonText":"the Fuchsia platform is not enabled for this project","fixText":"Run \"flutter create --platforms=fuchsia .\" in your application directory","fixCode":"create"}]},"custom":{"isSupported":false,"reasons":[{"reasonText":"the custom devices feature is not enabled","fixText":"Run \"flutter config --enable-custom-devices\"","fixCode":"config"}]}…
[3:22:03 PM] [FlutterDaemon] [Info] <== [{"id":"4","result":{"platforms":["web","android","ios","linux","macos","windows"],"platformTypes":{"web":{"isSupported":true},"android":{"isSupported":true},"ios":{"isSupported":true},"linux":{"isSupported":true},"macos":{"isSupported":true},"windows":{"isSupported":true},"fuchsia":{"isSupported":false,"reasons":[{"reasonText":"the Fuchsia feature is not enabled","fixText":"Run \"flutter config --enable-fuchsia\"","fixCode":"config"},{"reasonText":"the Fuchsia platform is not enabled for this project","fixText":"Run \"flutter create --platforms=fuchsia .\" in your application directory","fixCode":"create"}]},"custom":{"isSupported":false,"reasons":[{"reasonText":"the custom devices feature is not enabled","fixText":"Run \"flutter config --enable-custom-devices\"","fixCode":"config"}]}…
[3:22:03 PM] [General] [Info] Supported platforms for the workspace are web, android, ios, linux, macos, windows
[3:22:03 PM] [FlutterDaemon] [Info] <== [{"event":"device.added","params":{"id":"windows","name":"Windows","platform":"windows-x64","emulator":false,"category":"desktop","platformType":"windows","ephemeral":false,"emulatorId":null,"sdk":"Microsoft Windows [Version 10.0.26200.7171]","isConnected":true,"connectionInterface":"attached","capabilities":{"hotReload":true,"hotRestart":true,"screenshot":false,"fastStart":false,"flutterExit":true,"hardwareRendering":true,"startPaused":true}}}]
[3:22:03 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[3:22:03 PM] [DartToolingDaemon] [Info] ==> {"jsonrpc":"2.0","method":"postEvent","params":{"eventData":{"deviceId":"windows"},"eventKind":"deviceSelected","streamId":"Editor"}}
[3:22:03 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[3:22:03 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[3:22:03 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[3:22:03 PM] [DartToolingDaemon] [Info] ==> {"jsonrpc":"2.0","method":"postEvent","params":{"eventData":{"device":{"category":"desktop","emulator":false,"ephemeral":false,"id":"windows","name":"Windows","platform":"windows-x64","platformType":"windows","rawDeviceName":"Windows","supported":true}},"eventKind":"deviceAdded","streamId":"Editor"}}
[3:22:04 PM] [FlutterDaemon] [Info] <== [{"id":"2","result":[{"id":"Pixel_3a","name":"Pixel 3a","category":"mobile","platformType":"android"},{"id":"flutter_emulator","name":"flutter emulator","category":"mobile","platformType":"android"},{"id":"flutter_emulator_2","name":"flutter emulator 2","category":"mobile","platformType":"android"}]}]
[3:22:04 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[3:22:04 PM] [FlutterDaemon] [Info] <== [{"event":"device.added","params":{"id":"2B021FDH300DXJ","name":"Pixel 7 Pro","platform":"android-arm64","emulator":false,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":null,"sdk":"Android 16 (API 36)","isConnected":true,"connectionInterface":"attached","capabilities":{"hotReload":true,"hotRestart":true,"screenshot":true,"fastStart":true,"flutterExit":true,"hardwareRendering":true,"startPaused":true}}}]
[3:22:04 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[3:22:04 PM] [DartToolingDaemon] [Info] ==> {"jsonrpc":"2.0","method":"postEvent","params":{"eventData":{"deviceId":"2B021FDH300DXJ"},"eventKind":"deviceSelected","streamId":"Editor"}}
[3:22:04 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[3:22:04 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[3:22:04 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[3:22:04 PM] [DartToolingDaemon] [Info] ==> {"jsonrpc":"2.0","method":"postEvent","params":{"eventData":{"device":{"category":"mobile","emulator":false,"ephemeral":true,"id":"2B021FDH300DXJ","name":"Pixel 7 Pro","platform":"android-arm64","platformType":"android","rawDeviceName":"Pixel 7 Pro","supported":true}},"eventKind":"deviceAdded","streamId":"Editor"}}
[3:22:04 PM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"include_file_not_found","message":"The include file 'package:flutter_lints/flutter.yaml' in 'C:\\Users\\pcira\\Desktop\\flutter_application_1\\flutter_application_2\\analysis_options.yaml' can't be found when analyzing 'C:\\Users\\pcira\\Desktop\\flutter_application_1\\flutter_application_2'.","range":{"end":{"character":43,"line":0},"start":{"character":9,"line":0}},"severity":2,"source":"dart"}],"uri":"file:///C:/Users/pcira/Desktop/flutter_application_1/flutter_application_2/analysis_options.yaml"}}
[3:22:04 PM] [Analyzer] [Info] <== Content-Length: 97
Content-Type: application/vscode-jsonrpc; charset=utf-8
[3:22:04 PM] [Analyzer] [Info] <== {"id":3,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"ANALYZING"}}
[3:22:04 PM] [Analyzer] [Info] ==> Content-Length: 72
[3:22:04 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":3,"result":null,"clientRequestTime":1762978924404}
[3:22:04 PM] [FlutterDaemon] [Info] <== [{"event":"device.added","params":{"id":"chrome","name":"Chrome","platform":"web-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":false,"emulatorId":null,"sdk":"Google Chrome 142.0.7444.136","isConnected":true,"connectionInterface":"attached","capabilities":{"hotReload":true,"hotRestart":true,"screenshot":false,"fastStart":false,"flutterExit":false,"hardwareRendering":true,"startPaused":true}}}]
[3:22:04 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[3:22:04 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[3:22:04 PM] [DartToolingDaemon] [Info] ==> {"jsonrpc":"2.0","method":"postEvent","params":{"eventData":{"device":{"category":"web","emulator":false,"ephemeral":false,"id":"chrome","name":"Chrome","platform":"web-javascript","platformType":"web","rawDeviceName":"Chrome","supported":true}},"eventKind":"deviceAdded","streamId":"Editor"}}
[3:22:04 PM] [FlutterDaemon] [Info] <== [{"event":"device.added","params":{"id":"edge","name":"Edge","platform":"web-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":false,"emulatorId":null,"sdk":"Microsoft Edge 142.0.3595.53","isConnected":true,"connectionInterface":"attached","capabilities":{"hotReload":true,"hotRestart":true,"screenshot":false,"fastStart":false,"flutterExit":false,"hardwareRendering":true,"startPaused":true}}}]
[3:22:04 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[3:22:04 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[3:22:04 PM] [DartToolingDaemon] [Info] ==> {"jsonrpc":"2.0","method":"postEvent","params":{"eventData":{"device":{"category":"web","emulator":false,"ephemeral":false,"id":"edge","name":"Edge","platform":"web-javascript","platformType":"web","rawDeviceName":"Edge","supported":true}},"eventKind":"deviceAdded","streamId":"Editor"}}
[3:22:04 PM] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8
[3:22:04 PM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}}}Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8
[3:22:04 PM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"dart/textDocument/augmentation"},"timestamp":1762978924802}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"dart/textDocument/augmented"},"timestamp":1762978924802}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/codeAction"},"timestamp":1762978924802}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/codeLens"},"timestamp":1762978924802}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"dart/textDocumentContent"},"timestamp":1762978924803}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/documentColor"},"timestamp":1762978924803}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/colorPresentation"},"timestamp":1762978924803}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/documentHighlight"},"timestamp":1762978924803}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/documentSymbol"},"timestamp":1762978924803}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"dart/textDocument/editableArguments"},"timestamp":1762978924804}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"dart/textDocument/editArgument"},"timestamp":1762978924804}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"workspace/executeCommand"},"timestamp":1762978924804}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/onTypeFormatting"},"timestamp":1762978924804}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/rangeFormatting"},"timestamp":1762978924804}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/formatting"},"timestamp":1762978924804}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/hover"},"timestamp":1762978924804}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"dart/textDocument/imports"},"timestamp":1762978924805}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/implementation"},"timestamp":1762978924805}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"callHierarchy/incomingCalls"},"timestamp":1762978924805}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/inlineValue"},"timestamp":1762978924805}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"callHierarchy/outgoingCalls"},"timestamp":1762978924805}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/prepareCallHierarchy"},"timestamp":1762978924805}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/prepareTypeHierarchy"},"timestamp":1762978924805}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/signatureHelp"},"timestamp":1762978924806}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"dart/textDocument/super"},"timestamp":1762978924806}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"textDocument/typeDefinition"},"timestamp":1762978924806}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"typeHierarchy/subtypes"},"timestamp":1762978924806}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"typeHierarchy/supertypes"},"timestamp":1762978924806}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"workspace/willRenameFiles"},"timestamp":1762978924806}}
[3:22:04 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceRegistered","eventData":{"service":"Lsp","method":"workspace/symbol"},"timestamp":1762978924806}}
[3:22:05 PM] [General] [Info] Returning cached results for project search
[3:22:05 PM] [General] [Info] Returning cached results for project search
[3:22:22 PM] [General] [Info] Returning cached results for project search
[3:22:22 PM] [DevTools] [Info] ==> {"id":"1","method":"vscode.extensions.discover","params":{"rootPaths":["C:\\Users\\pcira\\Desktop\\flutter_application_1","C:\\Users\\pcira\\Desktop\\flutter_application_1\\flutter_application_2"]}}
[3:22:22 PM] [DevTools] [Info] <== {"id":"1","result":{"C:\\Users\\pcira\\Desktop\\flutter_application_1":{"extensions":[],"parseErrors":[]},"C:\\Users\\pcira\\Desktop\\flutter_application_1\\flutter_application_2":{"extensions":[],"parseErrors":[]}}}
[3:22:22 PM] [Analyzer] [Info] <== Content-Length: 97
Content-Type: application/vscode-jsonrpc; charset=utf-8
[3:22:22 PM] [Analyzer] [Info] <== {"id":4,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"ANALYZING"}}
[3:22:22 PM] [Analyzer] [Info] ==> Content-Length: 72
[3:22:22 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":4,"result":null,"clientRequestTime":1762978942464}
[3:22:22 PM] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}}}Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8
[3:22:22 PM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}}}
[3:23:10 PM] [DartToolingDaemon] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","eventKind":"ServiceUnregistered","eventData":{"service":"Lsp","method":"dart/textDocument/augmentation"},"timestamp":1762978990813}}
[3:23:10 PM] [DartToolingDaemon] [Info] DTD connection closed
[3:23:10 PM] [DartToolingDaemon] [Warn] Prompting to reload: (The Dart Tooling Daemon connection has terminated.) (actions: Reload, Show Log)
```

**Comment by DanTup** [comment]
Thanks for the log - it doesn't seem like there's anything obvious in there, it seems like DTD just shut down.

I will try adding some more logging here so that we get things like the exit code when it terminates (I think we are already logging `stderr` which makes me think there wasn't any stderr output in this case).

Could you also confirm exactly where the "FileSystemException: writeFrom failed" error is showing up (perhaps a screenshot)? Is this in the Debug Console when the app/debug session terminates?

**Comment by SenexTech** [comment]
Here are two screenshots.  The first shows the daemon message and then a minute or two latter the second screenshot of the FileSystemException error.  This was from a brand new project using VS Code (View/Command Pallete/Empty Application). Some more info that may help. Previously,  I have tried resintalling Flutter (twice), reinstalled VS Code, Updated Android to Android Studio Otter | 2025.2.1.  Here is the debug console output:

![Image](https://github.com/user-attachments/assets/472d597a-178e-4891-99b4-63025447e0b3)
![Image](https://github.com/user-attachments/assets/b0236609-bfd3-486a-ba72-5b178d88f2bc)

![Image](https://github.com/user-attachments/assets/01ea7d88-d6fa-439d-9723-2171d2e4309f)

`I/ex.fishoncanada(16784): Background concurrent mark compact GC freed 10MB AllocSpace bytes, 122(8268KB) LOS objects, 75% free, 21MB/85MB, paused 610us,3.232ms total 104.550ms
D/FirebaseSessions(16784): App backgrounded on com.senex.fishoncanada
D/Camera2PresenceSrc(16784): System onCameraAccessPrioritiesChanged.
D/Camera2PresenceSrc(16784): System onCameraAccessPrioritiesChanged.
D/Camera2PresenceSrc(16784): [FetchData] Refreshed camera list: CameraIdentifier{cameraIds=0}, CameraIdentifier{cameraIds=1}
D/Camera2PresenceSrc(16784): [FetchData] Refreshed camera list: CameraIdentifier{cameraIds=0}, CameraIdentifier{cameraIds=1}
D/ImeBackDispatcher(16784): Clear (mImeCallbacks.size=0)
D/ImeBackDispatcher(16784): switch root view (mImeCallbacks.size=0)
I/FA      (16784): Application backgrounded at: timestamp_millis: 1763041352054
I/ex.fishoncanada(16784): NativeAlloc concurrent mark compact GC freed 20MB AllocSpace bytes, 8(288KB) LOS objects, 75% free, 25MB/101MB, paused 511us,3.931ms total 118.453ms
Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: The pipe is being closed.
, errno = 232)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:1027:7)

#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:328:17)

#2      _rootRunUnary (dart:async/zone.dart:1546:13)

#3      _CustomZone.runUnary (dart:async/zone.dart:1429:19)

#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1329:7)

#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381:11)

#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312:7)

#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:798:19)

#8      _StreamController._add (dart:async/stream_controller.dart:663:7)

#9      _StreamController.add (dart:async/stream_controller.dart:618:5)

#10     _StreamSinkImpl.add (dart:io/io_sink.dart:155:17)

#11     _IOSinkImpl.write (dart:io/io_sink.dart:293:5)

#12     _StdSink._write (dart:io/stdio.dart:429:13)

#13     _StdSink.write (dart:io/stdio.dart:438:33)

#14     Stdio._stdioWrite.<anonymous closure> (package:flutter_tools/src/base/io.dart:378:14)
#15     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:108:32)
#16     _rootRun (dart:async/zone.dart:1525:13)

#17     _CustomZone.run (dart:async/zone.dart:1422:19)

#18     _runZoned (dart:async/zone.dart:2034:6)

#19     runZonedGuarded (dart:async/zone.dart:2020:12)

#20     asyncGuard (package:flutter_tools/src/base/async_guard.dart:106:3)
#21     Stdio._stdioWrite (package:flutter_tools/src/base/io.dart:376:5)
#22     Stdio.stdoutWrite (package:flutter_tools/src/base/io.dart:362:7)
#23     WindowsStdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger.dart:741:12)
#24     StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:537:5)
#25     DelegatingLogger.printStatus (package:flutter_tools/src/base/logger.dart:343:15)
#26     printStatus (package:flutter_tools/src/globals.dart:202:10)
#27     FlutterDevice.startEchoingDeviceLog.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:391:17)
#28     _rootRunUnary (dart:async/zone.dart:1538:47)

#29     _CustomZone.runUnary (dart:async/zone.dart:1429:19)

#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1329:7)

#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381:11)

#32     _DelayedData.perform (dart:async/stream_impl.dart:573:14)

#33     _PendingEvents.handleNext (dart:async/stream_impl.dart:678:11)

#34     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:649:7)

#35     _rootRun (dart:async/zone.dart:1517:47)

#36     _CustomZone.run (dart:async/zone.dart:1422:19)

#37     _CustomZone.runGuarded (dart:async/zone.dart:1321:7)

#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1362:23)

#39     _rootRun (dart:async/zone.dart:1525:13)

#40     _CustomZone.run (dart:async/zone.dart:1422:19)

#41     _CustomZone.runGuarded (dart:async/zone.dart:1321:7)

#42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1362:23)

#43     _microtaskLoop (dart:async/schedule_microtask.dart:40:35)

#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

#45     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:127:13)

#46     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194:5)


Exited (255).
`

![Image](https://github.com/user-attachments/assets/a2349bcf-6fec-4f37-9e97-61f4c99fad94)

![Image](https://github.com/user-attachments/assets/1c5a930c-1e2b-408f-9dfb-e95a69dece12)

**Comment by DanTup** [comment]
@bkonyi any thoughts on the exception above? It seems like the exception is occurring in the `flutter` tool, but it also goes through some `guard` methods that I assumed were to stop this kind of exception going unhandled.

Seems like it might be happening while trying to echo the device logs to stdout:

```
#23 WindowsStdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger.dart:741:12)
#24 StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:537:5)
#25 DelegatingLogger.printStatus (package:flutter_tools/src/base/logger.dart:343:15)
#26 printStatus (package:flutter_tools/src/globals.dart:202:10)
#27 FlutterDevice.startEchoingDeviceLog. (package:flutter_tools/src/resident_runner.dart:391:17)
```

Should we move this to flutter/flutter?

Seems a bit odd/suspicious that DTD is terminating at the same time.

**Comment by bkonyi** [comment]
It looks like the tool is in the process of exiting when that exception is thrown, since the `stdout` pipe has been closed. I'd be interested in seeing what the `--verbose` output would be first to verify what's happening before this exception is being thrown.

**Comment by DanTup** [comment]
>  I'd be interested in seeing what the `--verbose` output would be first to verify what's happening before this exception is being thrown.

@SenexTech is it possible you could collect a verbose log and see what's recorded at the end?

- Open the project and wait for analysis etc. to complete
- Run the **Dart: Collect Debugging Logs** command
- Run the app and wait for it to terminate (with the red exception text in the Debug Console)
- Click **Cancel** on the logging notification to stop logging and open the log file

Please reproduce this in a sample app and ensure there's nothing sensitive in the log before sharing.

Thanks!

**Comment by SenexTech** [comment]
Here is the log as requested

[logs.txt](https://github.com/user-attachments/files/23589351/logs.txt)

**Comment by DanTup** [comment]
@bkonyi doesn't seem like there's much in the verbose output. Filtering the log above to just the `flutter run` process stdout/stderr ends with:

```
[12:56:56 PM] [DAP] [Info] [Flutter (Pixel 7 Pro)] <== [Flutter] [+1026 ms] I/Choreographer(30475): Skipped 45 frames!  The application may be doing too much work on its main thread.
[12:56:56 PM] [DAP] [Info] [Flutter (Pixel 7 Pro)] <== [Flutter] [ +127 ms] D/ImeBackDispatcher(30475): switch root view (mImeCallbacks.size=0)
[12:56:56 PM] [DAP] [Info] [Flutter (Pixel 7 Pro)] <== [Flutter] [   +5 ms] D/InsetsController(30475): hide(ime())
[12:56:56 PM] [DAP] [Info] [Flutter (Pixel 7 Pro)] <== [Flutter] [        ] I/ImeTracker(30475): com.example.flutter_application_test:9479ffad: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
[12:56:59 PM] [DAP] [Info] [Flutter (Pixel 7 Pro)] <== [Flutter] [+3302 ms] D/ProfileInstaller(30475): Installing profile for com.example.flutter_application_test
[12:57:22 PM] [DAP] [Info] [Flutter (Pixel 7 Pro)] <== [Flutter] [+23032 ms] I/pplication_test(30475): Background concurrent mark compact GC freed 4023KB AllocSpace bytes, 4(76KB) LOS objects, 91% free, 2324KB/26MB, paused 836us,6.456ms total 112.337ms
[1:00:01 PM] [DAP] [Info] [Flutter (Pixel 7 Pro)] <== [Flutter] [stderr] Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: The pipe is being closed.

, errno = 232)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:1027:7)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:328:17)
...
```

There were a few `Flutter.Frame` events in between when viewing all of the log:

```
[12:56:56 PM] [DAP] [Info] [Flutter (Pixel 7 Pro)] <== [Flutter] [        ] I/ImeTracker(30475): com.example.flutter_application_test:9479ffad: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
[12:56:56 PM] [VmService] [Info] [Flutter (Pixel 7 Pro)] <== [VM] {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolateGroup":{"type":"@IsolateGroup","id":"isolateGroups/6236801084383503","name":"main.dart","number":"6236801084383503","isSystemIsolateGroup":false},"isolate":{"type":"@Isolate","id":"isolates/7009538461481007","name":"main","number":"7009538461481007","isSystemIsolate":false,"isolateGroupId":"isolateGroups/6236801084383503"},"timestamp":1763402216738,"extensionData":{"number":5,"startTime":464441312547,"elapsed":9096,"build":2163,"raster":768,"vsyncOverhead":6062}}}}
[12:56:56 PM] [VmService] [Info] [Flutter (Pixel 7 Pro)] <== [VM] {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolateGroup":{"type":"@IsolateGroup","id":"isolateGroups/6236801084383503","name":"main.dart","number":"6236801084383503","isSystemIsolateGroup":false},"isolate":{"type":"@Isolate","id":"isolates/7009538461481007","name":"main","number":"7009538461481007","isSystemIsolate":false,"isolateGroupId":"isolateGroups/6236801084383503"},"timestamp":1763402216738,"extensionData":{"number":6,"startTime":464441332827,"elapsed":3339,"build":1003,"raster":1426,"vsyncOverhead":756}}}}
[12:56:59 PM] [DAP] [Info] [Flutter (Pixel 7 Pro)] <== [Flutter] [+3302 ms] D/ProfileInstaller(30475): Installing profile for com.example.flutter_application_test
[12:57:22 PM] [DAP] [Info] [Flutter (Pixel 7 Pro)] <== [Flutter] [+23032 ms] I/pplication_test(30475): Background concurrent mark compact GC freed 4023KB AllocSpace bytes, 4(76KB) LOS objects, 91% free, 2324KB/26MB, paused 836us,6.456ms total 112.337ms
```

Nothing else that seems interesting (to my eyes) though.

**Comment by bkonyi** [comment]
The stack trace in these logs appears to be slightly different than the one reported before:

```
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:1027:7)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:328:17)
#2      _rootRunUnary (dart:async/zone.dart:1546:13)
#3      _CustomZone.runUnary (dart:async/zone.dart:1429:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1329:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:798:19)
#8      _StreamController._add (dart:async/stream_controller.dart:663:7)
#9      _StreamController.add (dart:async/stream_controller.dart:618:5)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:155:17)
#11     _IOSinkImpl.write (dart:io/io_sink.dart:293:5)
#12     _StdSink._write (dart:io/stdio.dart:429:13)
#13     _StdSink.write (dart:io/stdio.dart:438:33)
#14     Stdio._stdioWrite.<anonymous closure> (package:flutter_tools/src/base/io.dart:378:14)
#15     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:108:32)
#16     _rootRun (dart:async/zone.dart:1525:13)
#17     _CustomZone.run (dart:async/zone.dart:1422:19)
#18     _runZoned (dart:async/zone.dart:2034:6)
#19     runZonedGuarded (dart:async/zone.dart:2020:12)
#20     asyncGuard (package:flutter_tools/src/base/async_guard.dart:106:3)
#21     Stdio._stdioWrite (package:flutter_tools/src/base/io.dart:376:5)
#22     Stdio.stdoutWrite (package:flutter_tools/src/base/io.dart:362:7)
#23     WindowsStdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger.dart:741:12)
#24     StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:537:5)
#25     DelegatingLogger.printStatus (package:flutter_tools/src/base/logger.dart:343:15)
#26     VerboseLogger._emit (package:flutter_tools/src/base/logger.dart:1099:15)
#27     VerboseLogger.printTrace (package:flutter_tools/src/base/logger.dart:1036:5)
#28     DelegatingLogger.printTrace (package:flutter_tools/src/base/logger.dart:361:15)
#29     printTrace (package:flutter_tools/src/globals.dart:229:43)
#30     ResidentRunner._serviceProtocolDone (package:flutter_tools/src/resident_runner.dart:1332:13)
#31     _rootRunUnary (dart:async/zone.dart:1538:47)
#32     _CustomZone.runUnary (dart:async/zone.dart:1429:19)
<asynchronous suspension>
#33     ResidentRunner._serviceDisconnected (package:flutter_tools/src/resident_runn
```

The VM service connection appears to be disappearing. This, combined with the fact that the `stdio` pipes are closed tells me that something is killing the tool as the process's `stdio` pipes are closed by the consumer, not the tool itself. I'm not sure what could be causing that.

**Comment by DanTup** [comment]
@SenexTech is it possible you could open the project and once everything has settled down run this in a terminal:

```
code --status
```

It will provide some details about the workspace and the child processes.

Then, reproduce the issue (allow both the debug session to terminate, and DTD to terminate - but do not press the button to reload anything), and then run `code --status` again.

I'd be interested in seeing the processes before/after. In your original DTD log, although the DTD connection closes, it doesn't seem like the process actually terminated (we usually record the exit code and/or signal when it does).

Thanks!

**Comment by SenexTech** [comment]
I created 3 text files with the the ouput. The first is running Code --status a soon as the project is opened and before any crashes or exits. I then waited for the Daemon to crash and ran code --status again - 2nd file. Then I started project in debug and waited for phone to disconnect- 3rd file.  Hopefully this is what you are looking for but if not please let me know and I will try ag

[1-Initial project Start - no crash yet.txt](https://github.com/user-attachments/files/23607936/1-Initial.project.Start.-.no.crash.yet.txt)

[2-After Daemon crashes.txt](https://github.com/user-attachments/files/23607946/2-After.Daemon.crashes.txt)

[3-After Error and disconnect.txt](https://github.com/user-attachments/files/23607961/3-After.Error.and.disconnect.txt)

**Comment by DanTup** [comment]
@SenexTech thanks! Unfortunately there's not a lot revealing in there, although it does confirm that the DTD process did terminate despite not being logged in the way I would expect in your original log. I will do some testing to see if I can repro that and if so improve the logging (it might be useful to know if DTD terminated with an exit code or any stderr output).

I'm still puzzled that both DTD and the Flutter tool seem to be both terminating though. I don't _think_ either of them should terminate the other even if they crash.

**Comment by SenexTech** [comment]
Thanks for your help on this.  Let me know if you need anything else from me that may help.  As this issue is really affecting my ability to properly develop on my real app Im getting to the point of doing a complete re-install of my development machine including OS but really want to do this as a last resort.  Thoughts?

**Comment by DanTup** [comment]
@SenexTech I don't know how much it will help, but I have published a new pre-release extension that has a small tweak to the logging to ensure that if a process terminates with an exit code, we will log it into the extension log.

That means, if you get the latest pre-release (note: it may take 20-30mins to show up), and then repro the issue and run the **Dart: Open Extension Log** command after DTD terminates, you should get a line like:

```
[4:37:47 PM] [DartToolingDaemon] [Error] Process D:\Tools\Dart\Latest (Bleeding Edge)\bin\dart.exe terminated! 1, null
```

The last two values (`1, null`) are the exitCode and signal. I don't know how useful they will be, but it may be worth capturing them.

To switch to the Pre-release extension you can use this button in VS Code in the extension page:

<img width="703" alt="Dart pre-release versions" src="https://user-images.githubusercontent.com/1078012/218796750-90a70b0b-4957-468c-8eb4-688095cde112.png">


One other thing that might be useful to test (if you haven't already), is whether this only happens when you run the app through the VS Code debugger, or if you run from the terminal with `flutter run`, does is do the same?

If it _does not_ do the same, then trying as `flutter run --dtd-uri {dtdUri}` where `{dtdUri}` is replaced with the URI to DTD (which you can copy from VS code by running the **Dart: Copy DTD URI to Clipboard** command) might also be useful.

Thanks for your help and patience trying to get to the bottom of this!

**Comment by DanTup** [comment]
I got to mention the pre-release Dart extension you want is `v3.123.20251118` so if you get an earlier one (the last segment is the date in YYYYMMDD) you'll have to wait a while and check for updates. Be sure to "Restart Extensions" after installing the update.

**Comment by SenexTech** [comment]
I updated the extension to pre-release v3.123.20251118 and restarted extensions.  Stopped VS Code and re-opened the project in VS Code. Waited for the Daemon to terminate (did not run project) then ran the Dart: Open Extension Log and got the log results shown in  the attached log file.  

[Extension Log after Daemon stopped.txt](https://github.com/user-attachments/files/23613618/Extension.Log.after.Daemon.stopped.txt)

Also, one thing that didnt make sense to me were the lines below found in the log...
 // Add permission handling logic here
 // ...
 return await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);

The project I'm testing with is a brand new empty project with no references to Geolocator.  However, my real project does use Geolocator and  just so happens I was working on that portion of my real app earlier today. Just a corincidense? 

I tired your suggestions and ran through VS Code debugger and also run from terminal. Just need to mention that I dont need to run the project at all to have the Daemon teminate.  That happens when ever I open my project with VS code.  

1. Opened test project in VS Code, Selected Start Debugging from Run menu.  Project ran. Waited for approx 1 minute and the DTD terminated. Did not restart DTD. Waited another 1-2 minutes and got the "Unhandled exception: FileSystemException: writeFrom failed, path = '' (OS Error: The pipe is being closed., errno = 232)Exited message and my phone disconnected but app keeped running on phone.

2. Opened test project in VS Code. Typed Flutter Run in terminal.  The project ran . A minute or so later the DTD terminated.  Waited at least 10 minutes and never received the Unhandled exception as above and my phone never disconnected.

So looks like running through terminal does not yeild the same results.

Since #2 outcome was not the same I tried using Dart: Copy DTD URI to Clipboard to get the DTD URI but this command was unkown.  The only way I could find to get the URI was to use flutter run --print-dtd.  This printed the uri so I then  flutter run --dtd-url ws://127.0.0.1:64574/Q_dXk6EM0RA= which worked with the same outcome as #2 above.  Not sure if this was correctly done to give you the proper results.

**Comment by DanTup** [comment]
> Waited for the Daemon to terminate (did not run project) then ran the Dart: Open Extension Log and got the log results shown in the attached log file.

Thanks! Unfortunately this log still does not record the exit code from this process. I'm not sure why, this seems odd.

> Also, one thing that didnt make sense to me were the lines below found in the log...
> // Add permission handling logic here

Yes, I am also confused by this. Something is wrong here and I wonder if it might be related.

Could you try adding the following to your `.vscode/settings.json` (in this workspace):

```
"dart.flutterDaemonLogFile": "logs/flutter_daemon.txt",
```

Then reproduce the issue and grab a copy of that log file?

The output line in the log starts like this:

```
[2:55:36 PM] [General] [Info] Supported platforms for the workspace are web, android, ios, linux, macos, windowsFuture<Position> _determinePosition() async {
```

Which looks like there is some code embedded somewhere that only platform types should be listed. We get these values from the Flutter daemon, so I'm trying to understand if we got a bad response from the daemon, or if we're somehow messing the results up when they get back to the extension.

Thanks!

**Comment by DanTup** [comment]
(sorry, I hit send before finishing responding to the rest of your message)

> Just need to mention that I dont need to run the project at all to have the Daemon teminate. That happens when ever I open my project with VS code.

Ah, that's good to know - though it might mean there are two different issues here. Let's try to solve the DTD issue first (since it might be easier) in the hope they have the same cause.


> Since https://github.com/Dart-Code/Dart-Code/issues/2 outcome was not the same I tried using Dart: Copy DTD URI to Clipboard to get the DTD URI but this command was unkown.

Can you give a screenshot of exactly what you see here? Could you also (just after opening the project):

1. Click Help -> Toggle Developer Tools to open the Chromium developer tools
2. Click on the Console tab
3. See if there are any errors reported (in particularly, such as failing to activate Dart-Code)

Thanks!

**Comment by SenexTech** [comment]
I produced the requested logs but they didnt start as you described.  I did it 4 times with different log file names.  Hope this is is what you were looking for.

[senex3_flutter_daemon.txt](https://github.com/user-attachments/files/23629876/senex3_flutter_daemon.txt)
[flutter_daemon.txt](https://github.com/user-attachments/files/23629878/flutter_daemon.txt)
[senex_flutter_daemon.txt](https://github.com/user-attachments/files/23629877/senex_flutter_daemon.txt)
[senex2_flutter_daemon.txt](https://github.com/user-attachments/files/23629875/senex2_flutter_daemon.txt)

Here are the screenshots from the developer tools console

![Image](https://github.com/user-attachments/assets/f318812e-f0fa-4016-b72d-e930862f1bc5)

![Image](https://github.com/user-attachments/assets/d74eaa5e-d411-49d9-a73c-82439382a632)

**Comment by DanTup** [comment]
@SenexTech thanks! The console errors just show that the DTD connection is gone, but doesn't explain why.

There's nothing wrong with the supported platforms coming back from the daemon, so I'm going to look through the code again to see what's going on there.


> Since https://github.com/Dart-Code/Dart-Code/issues/2 outcome was not the same I tried using Dart: Copy DTD URI to Clipboard to get the DTD URI but this command was unkown.

Are you able to get a screenshot of what you see here? I'm still not sure why you'd get this error if the extension activated correctly.

**Comment by SenexTech** [comment]
So i was able to get the Dart: Copy DTD URI to Clipboard to work and ran the command below but got an error

PS C:\Users\pcira\Desktop\flutter_application_test> flutter run --dtd-uri=ws://127.0.0.1:55315/C_MFtMopgAw=
Could not find an option named "--dtd-uri".

also tried

PS C:\Users\pcira\Desktop\flutter_application_test> flutter run --dtd-uri ws://127.0.0.1:55315/C_MFtMopgAw=
Could not find an option named "--dtd-uri".

**Comment by DanTup** [comment]
@SenexTech apologies, it turns out [we don't currently pass DTD to `flutter run`](https://github.com/flutter/flutter/issues/177329). Based on your more recent comments I think DTD crashing might not be the cause of the app crashing though (although that doesn't mean they're not both crashing for similar reasons).

I'm going to publish an updated pre-release version once the bots complete, which I hope will capture the exit code/signal from DTD. It'll probably be ~30-60mins. If you want to update and try capturing the DTD log once that's done, maybe the exit code will help (although it is a bit of a long shot).

**Comment by DanTup** [comment]
I've published a new pre-release extension 3.123.20251119 (note the **9** at the end) that has some tweaks to logging when the process or websocket connection drop. Once you get that (it might take 30 mins), could you try capturing this log (note: this is DTD - the _tooling_ daemon, not the _Flutter_ daemon like before):

```
"dart.toolingDaemonLogFile": "logs/tooling_daemon.txt",
```

Then reproduce the issue until you see DTD terminate/disconnect, then grab a copy of that log.

Thanks again for your help trying to debug this!

**Comment by SenexTech** [comment]
Here is the tooling_daemon log

[tooling_daemon.txt](https://github.com/user-attachments/files/23632968/tooling_daemon.txt)

**Comment by DanTup** [comment]
@SenexTech thanks! This log seems to confirm that the DTD process is not actually terminating, only the WebSocket connection to it is closing.

Out of interest, do you know if you have any kind of proxy server (or antivirus that might use a proxy server) that might be sitting in between the VS Code extension and DTD? If so, could you try _temporarily_ disabling them to see if it makes any difference?

**Comment by SenexTech** [comment]
I do have Norton 360 and I disabled but it made no difference.  I also checked for proxy and I dont have any running.  I confirmed in settings and  with www.whatismyproxy.com.  I disabled all apps in my startup but still have issue.  I really dont want to but is it time to do a complete windows re-install on my machine? Its a lot of work but if we dont have any other options?  The thing is I had no issues at one time.  I have been using Flutter/Dart for months on this machine with no issues.  Not sure what changed that created this issue.  Should I try going back to a previous version of VS Code (I assume this possible)?

**Comment by DanTup** [comment]
@SenexTech unfortunately I don't currently have any bright ideas. I was going to ask if it just started with the new Flutter release recently, but I see you're on 3.35.7 (at least in the first post), so perhaps it's worth upgrading to the latest stable (3.38.2) on the off-chance something changed there.

Otherwise, if you want to try an older VS Code release there are download links along the top of https://code.visualstudio.com/updates/v1_105 to get older versions. You can also try older versions of the Dart extension by using this option:

<img width="666" height="363" alt="Image" src="https://github.com/user-attachments/assets/026f605f-6f01-4925-b071-291d73d1fe4a" />

Please let me know if any of these help, and I'll also ping back here if I think of anything else to try.

Thanks!

**Comment by SenexTech** [comment]
Woa!  This is new.  Tried to run Flutter Upgrade to latest as suggested and getting the following.  Not sure If I did someting doing all these tests.  

PS C:\Users\pcira\Desktop\flutter_application_test> flutter upgrade
Checking Dart SDK version... 
Downloading Dart SDK from Flutter engine ... 
Rename-Item : Access to the path 'C:\Users\pcira\dev\flutter\bin\cache\dart-sdk' is denied.
At C:\Users\pcira\dev\flutter\bin\internal\update_dart_sdk.ps1:74 char:9
+         Rename-Item $dartSdkPath "$oldDartSdkPrefix$oldDartSdkSuffix"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\pcira\...\cache\dart-sdk:String) [Rename-Item], IOException
    + FullyQualifiedErrorId : RenameItemIOError,Microsoft.PowerShell.Commands.RenameItemCommand
 
Error: Unable to update Dart SDK. Retrying... 

Waiting for 0 seconds, press CTRL+C to quit ...
Checking Dart SDK version... 
Downloading Dart SDK from Flutter engine ...
Rename-Item : Access to the path 'C:\Users\pcira\dev\flutter\bin\cache\dart-sdk' is denied.
At C:\Users\pcira\dev\flutter\bin\internal\update_dart_sdk.ps1:74 char:9
+         Rename-Item $dartSdkPath "$oldDartSdkPrefix$oldDartSdkSuffix"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\pcira\...\cache\dart-sdk:String) [Rename-Item], IOException
    + FullyQualifiedErrorId : RenameItemIOError,Microsoft.PowerShell.Commands.RenameItemCommand

Error: Unable to update Dart SDK. Retrying... 

Waiting for 0 seconds, press CTRL+C to quit ...
Checking Dart SDK version... 
Downloading Dart SDK from Flutter engine ... 
Rename-Item : Access to the path 'C:\Users\pcira\dev\flutter\bin\cache\dart-sdk' is denied.
At C:\Users\pcira\dev\flutter\bin\internal\update_dart_sdk.ps1:74 char:9
+         Rename-Item $dartSdkPath "$oldDartSdkPrefix$oldDartSdkSuffix"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\pcira\...\cache\dart-sdk:String) [Rename-Item], IOException
    + FullyQualifiedErrorId : RenameItemIOError,Microsoft.PowerShell.Commands.RenameItemCommand

Error: Unable to update Dart SDK after 3 retries. 
Could Not Find C:\Users\pcira\dev\flutter\bin\cache\engine-dart-sdk.stamp
PS C:\Users\pcira\Desktop\flutter_application_test>

**Comment by DanTup** [comment]
@SenexTech it sounds like those files are locked so the upgrade can't remove/replace them. I would try closing all instances of VS Code and if you still get the problem, try first running this in a (PowerShell) terminal window:

```
get-process dart | stop-process
```

(be sure you don't have any other important Dart processes running that you need, because this will stop them all)

If that still doesn't work, try rebooting and then run `flutter upgrade` in a terminal without first opening VS Code.

**Comment by Wsemm** [comment]
i face the same problem and i fix that by uninstalling the antivirus, i see latter that the antivirus was deleting or blocking some files for flutter

**Comment by SenexTech** [comment]
Yes, that was found to be the cause for me as well. I tried disabling the antivirus early in the debuging process but it made no difference.  It wasn't until I uninstalled Norton completly that it fixed my issue.  I have left Norton uninstalled and have not experienced any more issues.  Thanks for the comment and a big thanks to DanTup for all the help.

**Comment by DanTup** [comment]
@Wsemm @SenexTech can you both confirm exactly which antivirus program it was? Is it a free version? (I'd like to try and reproduce). Do you also know if there was any HTTP proxy component to it?

Thanks!

**Comment by SenexTech** [comment]
I use Norton 360 latest ver.  You can right click the Norton icon and disable the firewall and virus temporarily but that didn't fix it.  I had to uninstall Norton

**Comment by woopaddy** [comment]
I have experienced the same issue within the last 7 days.  I have had visual studio code and flutter on Windows PC for approx. past 15 months.  I have had Norton 360 on my pc for all this time.  My main focus in regards to flutter is working on flutter web app - have had NO issues at all in the past 15 months in using VS Code etc.  About a week ago I started experiencing the DTD terminating when debugging issue as described above.  I have come to the same conclusion it is Norton.  After uninstalling Norton 360 all worked as expected.

I have Windows 11 Pro and Norton Utilities Ultimate and Norton 360 Deluxe III.  I did the uninstall of Norton 360 and found all works well - no issue with DTD.  No issues with Norton Utilities Ultimate.  

I experimented again and reinstalled Norton 360 Deluxe III and the DTD terminated when debugging.  I then added to Norton360 settings to exclude scanning of my flutter sdk folder, .dartServer, my folder with the project files etc.  Also set in Norton specific exe's e.g. flutter\bin\cache\dart-sdk\bin\dartvm.exe.  I also made sure that in the Norton firewall rules, that UDP and TCP traffic was allowed for the dartvm.exe.  None of this made a difference - I continued to experience DTD terminating when debugging.

I uninstalled Norton 360 Deluxe III - and I no longer have this issue.  FYI, my Norton does automatic updates, so I suspect something about the latest Norton update has had an impact.  Note, the dartvm.exe is also set in my Windows Defender Firewall rules and there is NO issue.  Only with Norton 360.

I could not find any specific version number re Norton 360 Deluxe III.  I hope my findings can be of assistance.

Thanks.

**Comment by DanTup** [comment]
> I experimented again and reinstalled Norton 360 Deluxe III and the DTD terminated when debugging.

Thank you for testing this - this does help! I will do some testing and see if I can repro.

**Comment by DanTup** [comment]
Thank you all for your helping narrowing this down to Norton (something I would never have managed since I don't use it) :-)

I was able to reproduce this in a VM with Norton 360 installed. As described above, even with _everything_ in it disabled, the issue persists.

In all my logs, there was approximately 60s from the last payload over the socket when this happened - and the few logs above also show this.

So my theory is that Norton is proxying all of the connections (even those over the loopback) and an idle websocket is dropped after 60s regardless of whether it's actively scanning the content or not.

Spamming data over the socket in a quick test seemed to prevent it happening.

WebSockets have built-in support for ping/pong (usually for detecting connection drops), so I'm going to test with just calling `ping()` every 15-30s to keep the connection alive. It'll probably be tomorrow now, but I'll post back once I've verified this completely resolved the issue.

If it works, we might want to also implement this on the server sides (DTD and other services that use web sockets like this) and maybe also in DevTools where it's a web socket client (and maybe DAP / VM Service? it's possible you could pause at a breakpoint for 60s). (fyi @bkonyi @elliette)

@bkonyi I'm not sure this explains the other issue above (failing to write to stdout stream?), but I was also able to trigger that once while testing this, so I will do some more testing after I'm done with this.

**Comment by DanTup** [comment]
Also FYI @jwren since this might also affect IntelliJ.

**Comment by elliette** [comment]
SG! Thanks for investigating. As a side note, we were experiencing something similar with https://github.com/flutter/devtools/issues/9028 but the root cause was different. Chrome was putting the DevTools frame to sleep which would then close the DTD websocket connection. We ended up adding an `isClosed` method to the DTD API, but that was only because we couldn't keep pinging the websocket.

**Comment by DanTup** [comment]
@elliette ah, interesting - I hadn't considered that. I do also have another open issue about the sidebar inside VS Code losing its DTD connection which I wonder if might be the same issue as this one (and therefore having the ping enabled in DevTools and/or the DTD server might solve that) -> https://github.com/Dart-Code/Dart-Code/issues/5808. I've asked the OP to see if they use  Norton.

**Comment by DanTup** [comment]
@SenexTech @Wsemm @woopaddy I've have published new versions of the Dart extension today:

- v3.124.1 for stable
- v3.125.20251202 for pre-release

I've confirmed this resolves the issue with the DTD connection being dropped as first reported here. I'm also unable to reproduce the error with the debug session terminating with this fix (although I don't completely understand what was failing there, or how these would be related).

I can't be certain there aren't other issues with Norton installed, but we'll have to investigate them as they come up. I will apply this fix to some other places in the Dart tooling (such as the analysis servers connection to DTD) to ensure a similar problem does not occur elsewhere.

Thanks again for helping track this down!

**Comment by Abdelrahman-Hany** [comment]
I think the problem is related with spacific editor, as I was having Norton Antivirus and all was working well until I used Antigravity IDE. 

The problem happened to me before and was solved by resetting my pc then it appeared again when I used Antigravity, even though I was having Norton before, and it didn't appear
